[package]
name = "async-curl"
authors = ["Lorenzo Leonardo <enzotechcomputersolutions@gmail.com>"]
version = "0.1.6"
edition = "2021"
description = "This will perform curl Easy2 asynchronously for rust-lang using curl::multi and tokio"
license = "MIT"
repository = "https://github.com/LorenzoLeonardo/async-curl"
homepage = "https://github.com/LorenzoLeonardo/async-curl"
documentation = "https://docs.rs/async-curl"

[dependencies]
curl = { version = "0.4.44", features = ["default"] }
tokio = { version = "1.28.0", features = ["rt", "test-util", "macros", "time"] }
http = "0.2.9"

[dev-dependencies]
wiremock = "0.5.18"

[features]
multi = []